spring:
  application:
    name: Deal
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/creditbank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml

server:
  port: ${SERVER_PORT:8081}

client:
  calculator:
    url: ${CALCULATOR_URL:http://localhost:8080/calculator}
    path:
      offers: ${CALCULATOR_OFFERS_PATH:/offers}
      calc: ${CALCULATOR_CALC_PATH:/calc}

app:
  logging:
    http-filter-enabled: true
    level: DEBUG

retry:
  offers:
    attempts: 3
    delay: 1000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html