spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: Deal
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/creditbank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: credit
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml

kafka:
  init:
    topics: true
  topics:
    finishRegistration: finish-registration
    createDocuments: create-documents
    sendDocuments: send-documents
    sendSes: send-ses
    creditIssued: credit-issued
    statementDenied: statement-denied

server:
  port: ${SERVER_PORT:8081}

client:
  calculator:
    url: ${CALCULATOR_URL:http://localhost:8080/calculator}
    path:
      offers: ${CALCULATOR_OFFERS_PATH:/offers}
      calc: ${CALCULATOR_CALC_PATH:/calc}

app:
  errorhandling:
    enabled: true
  logging:
    http-filter-enabled: true
    level: DEBUG

retry:
  offers:
    attempts: 3
    delay: 1000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html