spring:
  application:
    name: Deal
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/creditbank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: INFO

client:
  calculator:
    url: ${CALCULATOR_URL:http://localhost:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html