spring:
  application:
    name: Statement

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: DEBUG
    org.springframework.retry: DEBUG

client:
  deal:
    url: ${DEAL_URL:http://localhost:8081/deal}
    path:
      statement: ${DEAL_OFFERS_PATH:/statement}
      select: ${DEAL_SELECT_PATH:/offer/select}

retry:
  offers:
    attempts: 3
    delay: 1000

prescoring:
  age:
    min: 18

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html