name: CI Dossier (build, tests, coverage, sonar, codecov)

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'dossier/**'
      - '.github/workflows/ci-dossier.yml'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'dossier/**'
      - '.github/workflows/ci-dossier.yml'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'

jobs:
  dossier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    env:
      MODULE_DIR: dossier
      SONAR_ORG: hzajax
      SONAR_PROJECT_KEY: DanilVolodin_CreditBank_dossier
      JAVA_VERSION: '21'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew :${{ env.MODULE_DIR }}:clean :${{ env.MODULE_DIR }}:build --no-daemon

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: ${{ env.MODULE_DIR }}
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src/main/java,src/main/kotlin
            -Dsonar.tests=src/test/java,src/test/kotlin
            -Dsonar.java.binaries=build/classes/java/main,build/classes/kotlin/main
            -Dsonar.junit.reportPaths=build/test-results/test
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ${{ env.MODULE_DIR }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: dossier
          fail_ci_if_error: true
          verbose: true
